name: auth_firebase
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.0
  fluttertoast: ^8.2.8
  image_picker: ^1.0.4
  google_fonts: ^6.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  uuid: ^4.5.1
  intl: ^0.20.2
  syncfusion_flutter_charts: ^29.2.10
  connectivity_plus: ^6.1.4
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.2  # Pour stocker le token localement
  provider: ^6.1.2

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/image.png
    - assets/images/project_team.png
    - assets/images/image0.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image2.png

#  fonts:
 #   - family: RecklessNeue
  #    fonts:
  #      - asset: assets/fonts/font/RecklessNeue-Bold.ttf
  #        weight: 700