// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjbifLQPnXKpnJ_VrFl-NC__g6b9Ro9o',
    appId: '1:155444341830:web:7d33fe3376075f7ef46e47',
    messagingSenderId: '155444341830',
    projectId: 'projetq-e875e',
    authDomain: 'projetq-e875e.firebaseapp.com',
    storageBucket: 'projetq-e875e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFiy8JxFqjUbc_xT4IE0QwgmoDybRiVN0',
    appId: '1:155444341830:android:21e15c23f356077ef46e47',
    messagingSenderId: '155444341830',
    projectId: 'projetq-e875e',
    storageBucket: 'projetq-e875e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_11g6FmruaY07mQdDsago56SUtcxd--8',
    appId: '1:155444341830:ios:88dabffbed460648f46e47',
    messagingSenderId: '155444341830',
    projectId: 'projetq-e875e',
    storageBucket: 'projetq-e875e.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_11g6FmruaY07mQdDsago56SUtcxd--8',
    appId: '1:155444341830:ios:4cdb05ecba510c61f46e47',
    messagingSenderId: '155444341830',
    projectId: 'projetq-e875e',
    storageBucket: 'projetq-e875e.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnjbifLQPnXKpnJ_VrFl-NC__g6b9Ro9o',
    appId: '1:155444341830:web:80898fb8c90d7af0f46e47',
    messagingSenderId: '155444341830',
    projectId: 'projetq-e875e',
    authDomain: 'projetq-e875e.firebaseapp.com',
    storageBucket: 'projetq-e875e.firebasestorage.app',
  );
}
